### ISSUE TITLE
"context descriptions" contradicts itself

### ISSUE THREAD

**Issue by bblack** [rubocop-hq/rspec-style-guide#16]
From https://github.com/reachlocal/rspec-style-guide#context-descriptions :

> context block descriptions should always start with 'when', and be in the form of a sentence with proper grammar.

It gives a "good example" of :

```rb
context 'when the display name is not present' do
```

Of course, "when the display name is not present" is not a sentence. It is a sentence fragment; more specifically, it is a noun phrase, or perhaps a dependent clause.

**Comment by pirj** [comment]
@separatio proposed the following, what do you think?

> `context` block descriptions should always start with 'when', and be in the form of a sentence with proper grammar when composed with `it` examples.
> Good Example:
```
context 'when the display name is not present' do
  it 'raises an error' do
```
