### ISSUE TITLE
Consider including `.rubocop.yml` file for use with `rubocop-rspec`

### ISSUE THREAD

**Issue by bazay** [rubocop-hq/rspec-style-guide#19]
I think it would be useful to include a sample `.rubocop.yml` file in this repo that developers could "plug-in" to their projects for quick automation of these rules.

**Comment by pirj** [comment]
[rubocop-rspec](https://github.com/rubocop-hq/rubocop-rspec) does a great job [providing `.rubocop.yml` with their distribution](https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml), and they try to comply with this guide as close as possible with the default options, still keeping them configurable.

**Comment by pirj** [comment]
[rubocop-rspec](https://github.com/rubocop-hq/rubocop-rspec) does a great job [providing `.rubocop.yml` with their distribution](https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml), and they try to comply with this guide as close as possible with the default options, still keeping them configurable.
