### ISSUE TITLE
Merge betterspecs

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rspec-style-guide#26]
The development of betterspecs [has stuck](https://github.com/lelylan/betterspecs/issues/153), it's been a long while that http://www.betterspecs.org/ has not been updated (uses `master` branch), and the latest (`gh-pages` branch) reside on http://lelylan.github.io/betterspecs, but is mostly inactive, and those two are out of sync.
Also consider checking [open pull requests](https://github.com/lelylan/betterspecs/pulls).

**Comment by bbatsov** [comment]
Maybe we can just publish something similar to a different domain? I assume that'd be much easier than trying to update `betterspecs.org`.

**Comment by pirj** [comment]
Resolved in #55
