### ISSUE TITLE
Digest the answers to commonly asked questions from a regarded source

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rspec-style-guide#27]
An AMA (ask me anything) has been [recently held on Reddit]( https://www.reddit.com/r/ruby/comments/73nrhk/ama_the_authors_of_effective_testing_with_rspec_3) with the authors of "Effective Testing with RSpec 3", Myron Marston and Ian Dees, there are some very interesting points worth being mentioned in this style guide.

**Comment by bbatsov** [comment]
Nice find!

**Comment by pirj** [comment]
Digested what was in there, also added my personal notes and some interesting points I've spotted in Myron/Ian's Effective testing with RSpec` book so far. Related issues: from #56 to #74.
