### ISSUE TITLE
Describe when to use `specify`

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rspec-style-guide#41]
> Frankly, I've never really needed it, but I guess we should outline some good use cases for it.

**Comment by bbatsov** [comment]
Yeah, guess this will be a hard one. :-)

**Comment by pirj** [comment]
That's definitely a hard sell.
As RSpec defines it:
> Useful for when your docstring does not read well off of `it`.

```
RSpec.describe MyClass do
  specify "#do_something is deprecated" do
```

An example from their own code base:
```
describe "#force" do
  context "for ordering options" do
    specify "CLI `--seed 37` forces order and seed" do
```

**Comment by bbatsov** [comment]
Interesting. Most often I've seen it used without any description but that example makes perfect sense. How does this look in the output, btw?

**Comment by pirj** [comment]
The output is (both examples consolidated):
```
root
  MyClass
    #do_something is deprecated (FAILED - 1)
  #force
    for ordering options
      CLI `--seed 37` forces order and seed
```
