### ISSUE TITLE
Mention rubocop-rspec

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rspec-style-guide#83]
It's probably worth mentioning that https://github.com/rubocop-hq/rubocop-rspec can check for many of the things described here.

**Comment by bbatsov** [comment]
Totally agree. I think we should also audit the `rubocop-rspec` config, so it's more or less aligned with the guide. This topic came up [here](https://www.reddit.com/r/ruby/comments/bhnc1c/the_rspec_style_guide_reloaded/). 

We should probably also check if there are some good practices enforced by `rubocop-rspec` that are worth adding to the guide.
