### ISSUE TITLE
Review advice for "When several tests relate to the same subject"

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rspec-style-guide#86]
> When several tests relate to the same subject, use subject to reduce repetition.
https://github.com/rubocop-hq/rspec-style-guide#subject

I think this takes DRY too far. It adds level of indirection with very negligible benefit.

**Comment by pirj** [comment]
There is a lengthy discussion about this one [here](https://github.com/lelylan/betterspecs/issues/7).

There is also a [named subject](https://github.com/rubocop-hq/rspec-style-guide/blob/master/README.md#use-subject) recommendation that helps reducing the indirection.

**Comment by andyw8** [comment]
Ok, this seems to be quite a controversial one. I'm going to put it on hold for now.
