### ISSUE TITLE
Convert to AsciiDoc

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rspec-style-guide#95]
In light of #87 I think it'd be nice if we adopted a better format for the guide, namely AsciiDoc. It would allow us to have native admonitions, footnotes, sane nesting of list items, etc and to easily export the guide in various formats. That would also make it trivial to publish a simple site from the guide down the road if we want to.

It's trivial to convert to AsciiDoc with this tool https://github.com/asciidoctor/kramdown-asciidoc (created by the maintainer of AsciiDoctor himself). 

In general my longer term plan is to convert all guides to AsciiDoc and maybe even RuboCop's own documentation.

**Comment by bbatsov** [comment]
You might find this article https://asciidoctor.org/docs/asciidoc-vs-markdown/ and the links at its bottom an interesting read.

**Comment by pirj** [comment]
Agree, I have very positive experience with AsciiDoc. And this guide is a good starting point.

**Comment by bbatsov** [comment]
Great! Would you tackle the conversation yourself?

**Comment by pirj** [comment]
Yes, definitely.
